// <auto-generated />
using DrinksServiceApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace drinksservicevs.Migrations
{
    [DbContext(typeof(VendingContext))]
    partial class VendingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DrinkModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("count");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.HasKey("id");

                    b.ToTable("DrinksList");
                });

            modelBuilder.Entity("VendingModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("blocked1");

                    b.Property<bool>("blocked10");

                    b.Property<bool>("blocked2");

                    b.Property<bool>("blocked5");

                    b.Property<int>("cash");

                    b.HasKey("id");

                    b.ToTable("VendingModels");
                });
#pragma warning restore 612, 618
        }
    }
}
